### PR TITLE
Fix file extension being set to mp4

### LINKED ISSUE #3: Wrong format of downloaded audio tracks
The downloaded audio tracks are of .mp4 (used for video) format instead of something for audio like .mp3.

### PR DESCRIPTION
**Pull request by BijanRegmi**
Fixes #3

### CODE REVIEW

**Review by Veerhan-glitch — CHANGES_REQUESTED** [review]
1) umm sorry but i am getting an error (AttributeError: 'NoneType' object has no attribute 'span') on line 17 can you pls check that
2) if i understood the code right currently it only forks for the signal track section and not the whole playlist right?

**Comment by BijanRegmi** [comment]
Can't seem to recreate this. Can you specify which video you tried to download?

Also, [this](https://stackoverflow.com/a/65226424/13001607) post from stackoverflow says it's due to old version of pytube. Maybe update pytube and try?

I tried 4 videos and all seem to work fine. This is my pytube version:
```
$ pip show pytube
Name: pytube
Version: 12.1.0
Summary: Python 3 library for downloading YouTube Videos.
Home-page: https://github.com/pytube/pytube
Author: Ronnie Ghose, Taylor Fox Dahlin, Nick Ficano
Author-email: hey@pytube.io
License: The Unlicense (Unlicense)
Location: /home/immo/.local/lib/python3.10/site-packages
Requires: 
Required-by: 
```

**Comment by Veerhan-glitch** [comment]
oh yea mb my pytube was not of the latest version
also can you pls also conform if this also works for a playlist?

**Comment by BijanRegmi** [comment]
Yes it now works with playlists as well
Commit 48733ee makes the following changes:
- Fix file format while downloading playlist songs
- Handle errors with try catch block
- Print title of every video being downloaded from the playlist

**Comment by Veerhan-glitch** [comment]
Thanks for contributing
happy hactoberfest

**Pull request merged**
